### ISSUE TITLE
Implement Length Argument on Signal

### ISSUE THREAD

**Issue by wwatkins102** [pawnPhilosopher/lossy#1]
As well as choosing primary line constants, also give option to choose the length of transmission line in between each drop-off. Might want to automate the LTSpice execution as this will result in many more executions. 1331 different line constant combinations and 5 different Cdrps and now 10 different line lengths, the number of combinations is 66550 different waveforms, each in 50 different LTSpice executions.

**Comment by danrotsy** [comment]
ill add the option to display in main.py

**Comment by danrotsy** [comment]
length added with selection and simulation
